repeat_time: 5
log_path: OURS
folds: 5
unique_id: ""

dataset:
  name: abide
  batch_size: 16
  test_batch_size: 16
  val_batch_size: 16
  train_set: 0.7
  val_set: 0.1
  path: /media/SSD2/MindGraphs/ABIDE_data/abide_D16_S8.npy
  stratified: True
  drop_last: True

model:
  name: BrainNetworkTransformer
  sizes: [360, 10]  # Note: The input node size should not be included here
  pooling: [false, true]
  pos_encoding: none  # identity, none
  orthogonal: true
  freeze_center: true
  project_assignment: true
  pos_embed_dim: 360

training:
  name: Train
  epochs: 200

